# Generated by Django 3.0.7 on 2020-06-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_private_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Private_Info',
        ),
    ]
